
server:
  port: 10086  # 应用端口

spring:
  application:
    name: eureka-server  # 应用名称，会在Eureka中显示

eureka:
  server:
    # 两个缓存之间的同步更新时间
    response-cache-update-interval-ms: 5000
    eviction-interval-timer-in-ms: 6000 # 多久检查一次心跳
  client:
    #register-with-eureka: false  # 是否注册自己的信息到EurekaServer，默认是true
    #fetch-registry: false        # 是否拉取其它服务的信息，默认是true
    service-url:   # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10087/eureka
    # 去注册中心拉取可用服务列表时间间隔
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 心跳上报时间，默认30s
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
